"use client";

import { useActionState } from "react";
import { rotateMachineTokenAction, updateMachineAction } from "@/app/admin/machines/actions";

type Machine = { id: string; machine_code: string; machine_name: string; location: string | null; status: string; hasToken: boolean };

export function MachineAdminCard({ machine }: { machine: Machine }) {
  const [saveState, saveAction, saving] = useActionState(updateMachineAction, { ok: false });
  const [tokenState, tokenAction, rotating] = useActionState(rotateMachineTokenAction, { ok: false });
  return <article className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">{machine.machine_code}</p><h2 className="mt-1 text-xl font-semibold">{machine.machine_name}</h2></div><span className={`h-3 w-3 rounded-full ${machine.status === "available" ? "bg-emerald-500" : "bg-slate-300"}`} /></div><form action={saveAction} className="mt-5 space-y-3"><input type="hidden" name="machineId" value={machine.id} /><input name="machineName" defaultValue={machine.machine_name} required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><input name="location" defaultValue={machine.location ?? ""} placeholder="สถานที่" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><select name="status" defaultValue={machine.status} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="available">พร้อมให้จอง</option><option value="maintenance">ซ่อมบำรุง</option><option value="inactive">ยังไม่เปิดใช้</option><option value="disabled">ปิดใช้งาน</option></select><button disabled={saving} className="w-full rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{saving ? "กำลังบันทึก…" : "บันทึกข้อมูล"}</button>{saveState.message ? <p className={`text-xs font-semibold ${saveState.ok ? "text-emerald-700" : "text-rose-700"}`}>{saveState.message}</p> : null}</form><div className="mt-5 border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><p className="text-sm font-semibold">TimeLockApp Token</p><span className="text-xs text-slate-500">{machine.hasToken ? "ตั้งค่าแล้ว" : "ยังไม่มี"}</span></div><form action={tokenAction} className="mt-3"><input type="hidden" name="machineId" value={machine.id} /><button disabled={rotating} className="w-full rounded-xl border border-amber-300 bg-amber-50 px-4 py-2.5 text-sm font-semibold text-amber-900 hover:bg-amber-400">{rotating ? "กำลังสร้าง…" : machine.hasToken ? "หมุนเวียน Token" : "สร้าง Token"}</button></form>{tokenState.deviceToken ? <div className="mt-3 rounded-xl bg-slate-950 p-3 text-white"><p className="text-[11px] font-bold uppercase tracking-wider text-amber-400">แสดงครั้งเดียว — คัดลอกตอนนี้</p><code className="mt-2 block break-all text-xs">{tokenState.deviceToken}</code></div> : null}{tokenState.message ? <p className={`mt-2 text-xs ${tokenState.ok ? "text-emerald-700" : "text-rose-700"}`}>{tokenState.message}</p> : null}</div></article>;
}
