import { redirect } from "next/navigation";
import { AdminNav } from "@/components/admin/admin-nav";
import { AdminCancelBookingButton } from "@/components/admin/admin-cancel-booking-button";
import { requireAdminIdentity } from "@/lib/auth/identity";
import { listAdminBookings } from "@/lib/admin/sheet-repository";

const allowedStatuses = ["all", "confirmed", "app_pending", "app_received", "active", "completed", "cancelled", "expired"];

export default async function AdminBookingsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const { q = "", status = "all" } = await searchParams;
  const selectedStatus = allowedStatuses.includes(status) ? status : "all";
  await requireAdminIdentity().catch(() => redirect("/admin"));
  const normalizedQuery = q.trim().toLowerCase();
  const rows = (await listAdminBookings()).filter((row) => (selectedStatus === "all" || row.status === selectedStatus) && (!normalizedQuery || [row.bookingNumber, row.machineCode, row.email, row.name].some((value) => value.toLowerCase().includes(normalizedQuery))));

  return <main className="min-h-screen bg-white text-slate-950"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-12"><AdminNav /><header className="mt-14"><p className="text-xs font-bold uppercase tracking-[0.28em] text-amber-600">BOOKING OPERATIONS</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">รายการจองทั้งหมด</h1></header><form className="mt-8 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><input name="q" defaultValue={q} placeholder="ค้นหาเลขที่การจอง" className="min-w-64 flex-1 rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-amber-500" /><select name="status" defaultValue={selectedStatus} className="rounded-xl border border-slate-200 px-4 py-3"><option value="all">ทุกสถานะ</option>{allowedStatuses.slice(1).map((value) => <option key={value} value={value}>{value}</option>)}</select><button className="rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white">ค้นหา</button></form><section className="mt-6 overflow-x-auto rounded-[1.5rem] border border-slate-200 bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Booking</th><th className="p-4">ผู้จอง</th><th className="p-4">เครื่อง</th><th className="p-4">ระยะเวลา</th><th className="p-4">สถานะ</th><th className="p-4">จัดการ</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.bookingId}><td className="p-4 font-semibold">{row.bookingNumber}</td><td className="p-4"><p>{row.name}</p><p className="text-xs text-slate-500">{row.email}</p></td><td className="p-4 font-semibold">{row.machineCode}</td><td className="p-4"><p className="font-semibold">ใช้งานได้ 3 ชั่วโมง</p><p className="text-xs text-slate-500">เริ่มนับเมื่อ login เข้า TimeLock</p></td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{row.status}</span></td><td className="p-4">{!["completed", "cancelled", "expired"].includes(row.status) ? <AdminCancelBookingButton bookingId={row.bookingId} /> : "—"}</td></tr>)}{rows.length === 0 ? <tr><td colSpan={6} className="p-14 text-center text-slate-500">ไม่พบรายการจอง</td></tr> : null}</tbody></table></section></div></main>;
}
